# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default=2, upload_to='reddit'),
            preserve_default=False,
        ),
    ]
