# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-20 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditor', '0003_auto_20200220_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
